version: '3'

services:
  userdb:
    build: ./login/sql
    image: mysql:8.0
    container_name: user_db
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: userRoot
      MYSQL_DATABASE: userdb
      MYSQL_USER: service_user
      MYSQL_PASSWORD: service_user
    ports:
      - "9906:3306"
    expose:
      - "9906"
    networks:
      - main_network

  web:
    build: ./login/php
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - userdb
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8000:80"
    networks:
      - main_network
    stdin_open: true
    tty: true

  recipedb:
    build: ./recipe/sql
    image: mysql:8.0
    volumes:
      - reciped:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: recipeRoot
      MYSQL_DATABASE: RecipeDb
      MYSQL_USER: recipe_user
      MYSQL_PASSWORD: recipe_user
    ports:
      - "9907:3306"
    networks:
      - main_network

  recipeweb:
    image: recipe-service:latest
    build: ./recipe
    restart: on-failure
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://recipedb:3306/RecipeDb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: recipeRoot
    depends_on:
      - recipedb
    networks:
      - main_network

  kitchendb:
    build: ./kitchen/sql
    image: mysql:8.0
    volumes:
      - kitchend:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kitchenRoot
      MYSQL_DATABASE: KitchenDb
      MYSQL_USER: kitchen_user
      MYSQL_PASSWORD: kitchen_user
    ports:
      - "9908:3306"
    networks:
      - main_network

  kitchenweb:
    image: kitchen-service:latest
    build: ./kitchen
    restart: on-failure
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://kitchendb:3306/KitchenDb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kitchenRoot
    depends_on:
      - kitchendb
    networks:
      - main_network

  orderdb:
    build: ./main/sql
    image: mysql:8.0
    volumes:
      - orderd:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: orderRoot
      MYSQL_DATABASE: OrderDb
      MYSQL_USER: order_user
      MYSQL_PASSWORD: order_user
    ports:
      - "9909:3306"
    networks:
      - main_network

  mainweb:
    image: main-service:latest
    build: ./main
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://orderdb:3306/OrderDb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: orderRoot
    depends_on:
      - orderdb
    networks:
      - main_network

volumes:
  dbdata:
  reciped:
  kitchend:
  orderd:

networks:
  main_network:
    driver: bridge