use OrderDb;
go

CREATE TABLE order_table
(
ORDER_ID INT NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(20),
PRIMARY KEY (ORDER_ID)
);
go

CREATE TABLE order_item
(
ID INT NOT NULL AUTO_INCREMENT,
ORDER_ID INT,
KITCHEN_ID INT,
RECIPE_ID INT,
QUANTITY INT,
PRIMARY KEY (ID),
FOREIGN KEY (ORDER_ID)
REFERENCES order_table(order_id)
);
go

CREATE TABLE basket
(
BASKET_ID INT NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(20),
PRIMARY KEY (BASKET_ID),
UNIQUE KEY (USERNAME)
);
go

CREATE TABLE basket_item
(
ID INT NOT NULL AUTO_INCREMENT,
BASKET_ID INT,
KITCHEN_ID INT,
RECIPE_ID INT,
QUANTITY INT,
PRIMARY KEY (ID),
FOREIGN KEY (BASKET_ID)
REFERENCES basket(basket_id)
);
go